// <auto-generated />
using System;
using JewerlyBack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JewerlyBack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251208195639_RefreshJewelryBaseModelsWithCanonicalSet")]
    partial class RefreshJewelryBaseModelsWithCanonicalSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JewerlyBack.Models.AiPreviewJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiConfigJson")
                        .HasColumnType("text");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FramesJson")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("GuestClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prompt")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("SingleImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("Status");

                    b.HasIndex("GuestClientId", "Status")
                        .HasFilter("\"GuestClientId\" IS NOT NULL");

                    b.ToTable("AiPreviewJobs");
                });

            modelBuilder.Entity("JewerlyBack.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Provider", "ExternalId")
                        .HasFilter("\"Provider\" IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryBaseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PreviewImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("JewelryBaseModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            BasePrice = 250.0m,
                            CategoryId = 1,
                            Code = "classic_solid_band",
                            Description = "Simple solid metal band with smooth polished surface, uniform width throughout",
                            IsActive = true,
                            Name = "Classic Solid Band"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            BasePrice = 400.0m,
                            CategoryId = 1,
                            Code = "thin_band_single_stone",
                            Description = "Delicate thin band featuring one small stone set in a minimal prong or bezel setting",
                            IsActive = true,
                            Name = "Thin Band with Single Stone"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            BasePrice = 800.0m,
                            CategoryId = 1,
                            Code = "solitaire_engagement_ring",
                            Description = "Classic engagement ring with a prominent center stone elevated in a four or six-prong setting on a slender band",
                            IsActive = true,
                            Name = "Solitaire Engagement Ring"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            BasePrice = 950.0m,
                            CategoryId = 1,
                            Code = "eternity_ring",
                            Description = "Band fully encircled with small identical stones set side-by-side in a continuous channel or prong setting",
                            IsActive = true,
                            Name = "Eternity Ring"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            BasePrice = 450.0m,
                            CategoryId = 1,
                            Code = "signet_ring",
                            Description = "Broad band with a flat rectangular or oval top surface suitable for engraving or decorative elements",
                            IsActive = true,
                            Name = "Signet Ring"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            BasePrice = 300.0m,
                            CategoryId = 2,
                            Code = "classic_stud",
                            Description = "Simple stud earring with a single gemstone set directly on a post, minimalist and close to the earlobe",
                            IsActive = true,
                            Name = "Classic Stud"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            BasePrice = 450.0m,
                            CategoryId = 2,
                            Code = "cluster_stud",
                            Description = "Stud earring featuring multiple small stones arranged in a tight cluster around a central stone",
                            IsActive = true,
                            Name = "Cluster Stud"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            BasePrice = 220.0m,
                            CategoryId = 2,
                            Code = "small_hoop",
                            Description = "Smooth metal hoop in a small diameter, simple circular shape that hugs the earlobe",
                            IsActive = true,
                            Name = "Small Hoop"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            BasePrice = 550.0m,
                            CategoryId = 2,
                            Code = "hoop_with_stones",
                            Description = "Hoop earring with small stones set along the outer edge, adding sparkle to the classic hoop design",
                            IsActive = true,
                            Name = "Hoop with Stones"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            BasePrice = 380.0m,
                            CategoryId = 2,
                            Code = "simple_drop_earring",
                            Description = "Earring with a single stone or element suspended below the earlobe on a short chain or wire",
                            IsActive = true,
                            Name = "Simple Drop Earring"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            BasePrice = 180.0m,
                            CategoryId = 3,
                            Code = "round_disc_pendant",
                            Description = "Flat circular disc pendant with smooth surface, ideal for engraving or minimal embellishment",
                            IsActive = true,
                            Name = "Round Disc Pendant"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            BasePrice = 200.0m,
                            CategoryId = 3,
                            Code = "bar_pendant_vertical",
                            Description = "Slender vertical bar pendant with clean lines and modern aesthetic, suspended by the top edge",
                            IsActive = true,
                            Name = "Bar Pendant (Vertical)"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            BasePrice = 220.0m,
                            CategoryId = 3,
                            Code = "heart_outline_pendant",
                            Description = "Open heart shape formed by a thin metal outline, romantic and delicate design",
                            IsActive = true,
                            Name = "Heart Outline Pendant"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            BasePrice = 350.0m,
                            CategoryId = 3,
                            Code = "single_stone_pendant",
                            Description = "Single prominent gemstone held in a prong or bezel setting, suspended from a chain as the focal point",
                            IsActive = true,
                            Name = "Single Stone Pendant"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            BasePrice = 190.0m,
                            CategoryId = 3,
                            Code = "open_circle_pendant",
                            Description = "Circular ring pendant with open center, representing continuity and eternity",
                            IsActive = true,
                            Name = "Open Circle Pendant"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            BasePrice = 280.0m,
                            CategoryId = 4,
                            Code = "chain_small_central_pendant",
                            Description = "Delicate chain with a small decorative pendant or charm positioned at the center front",
                            IsActive = true,
                            Name = "Chain with Small Central Pendant"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            BasePrice = 1200.0m,
                            CategoryId = 4,
                            Code = "tennis_necklace",
                            Description = "Continuous line of identical stones set in individual settings, creating a sparkling collar effect",
                            IsActive = true,
                            Name = "Tennis Necklace"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            BasePrice = 220.0m,
                            CategoryId = 4,
                            Code = "minimal_choker_band",
                            Description = "Simple thin metal band that sits snugly around the neck, modern and streamlined",
                            IsActive = true,
                            Name = "Minimal Choker Band"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            BasePrice = 250.0m,
                            CategoryId = 4,
                            Code = "name_plate_necklace",
                            Description = "Horizontal rectangular plate attached to a chain, designed for personalized name or word engraving",
                            IsActive = true,
                            Name = "Name Plate Necklace"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            BasePrice = 280.0m,
                            CategoryId = 5,
                            Code = "chain_bracelet",
                            Description = "Flexible linked chain bracelet with clasp closure, elegant and adjustable",
                            IsActive = true,
                            Name = "Chain Bracelet"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            BasePrice = 320.0m,
                            CategoryId = 5,
                            Code = "solid_bangle",
                            Description = "Rigid circular bracelet in solid metal, slips over the hand without a clasp",
                            IsActive = true,
                            Name = "Solid Bangle"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            BasePrice = 950.0m,
                            CategoryId = 5,
                            Code = "tennis_bracelet",
                            Description = "Line bracelet with a continuous row of individually set stones linked together",
                            IsActive = true,
                            Name = "Tennis Bracelet"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            BasePrice = 300.0m,
                            CategoryId = 5,
                            Code = "charm_bracelet",
                            Description = "Chain bracelet with attachment points for hanging decorative charms or pendants",
                            IsActive = true,
                            Name = "Charm Bracelet"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            BasePrice = 150.0m,
                            CategoryId = 6,
                            Code = "cable_chain",
                            Description = "Classic chain with uniform oval or round links connected in a simple alternating pattern",
                            IsActive = true,
                            Name = "Cable Chain"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            BasePrice = 170.0m,
                            CategoryId = 6,
                            Code = "curb_chain",
                            Description = "Chain with interlocking uniform links that lie flat when worn, creating a smooth surface",
                            IsActive = true,
                            Name = "Curb Chain"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            BasePrice = 160.0m,
                            CategoryId = 6,
                            Code = "figaro_chain",
                            Description = "Chain with alternating pattern of short and long oval links, typically three short links followed by one elongated link",
                            IsActive = true,
                            Name = "Figaro Chain"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000004"),
                            BasePrice = 200.0m,
                            CategoryId = 6,
                            Code = "rope_chain",
                            Description = "Chain with small links twisted together to resemble rope texture, creating a thick and durable design",
                            IsActive = true,
                            Name = "Rope Chain"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000005"),
                            BasePrice = 180.0m,
                            CategoryId = 6,
                            Code = "box_chain",
                            Description = "Chain with square links forming a smooth, continuous tube-like appearance",
                            IsActive = true,
                            Name = "Box Chain"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            BasePrice = 280.0m,
                            CategoryId = 7,
                            Code = "floral_brooch",
                            Description = "Decorative pin with flower-inspired design featuring petals and possibly a center stone",
                            IsActive = true,
                            Name = "Floral Brooch"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            BasePrice = 220.0m,
                            CategoryId = 7,
                            Code = "geometric_bar_brooch",
                            Description = "Horizontal bar pin with clean geometric lines and modern aesthetic",
                            IsActive = true,
                            Name = "Geometric Bar Brooch"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000003"),
                            BasePrice = 300.0m,
                            CategoryId = 7,
                            Code = "animal_shape_brooch",
                            Description = "Decorative pin shaped like an animal or creature, often embellished with stones or enamel",
                            IsActive = true,
                            Name = "Animal Shape Brooch"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000004"),
                            BasePrice = 250.0m,
                            CategoryId = 7,
                            Code = "monogram_brooch",
                            Description = "Pin featuring stylized initials or letters in an elegant font design",
                            IsActive = true,
                            Name = "Monogram Brooch"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000001"),
                            BasePrice = 120.0m,
                            CategoryId = 9,
                            Code = "labret_stud",
                            Description = "Flat-back piercing stud with decorative front, suitable for lip, ear cartilage, or other piercings",
                            IsActive = true,
                            Name = "Labret Stud"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000002"),
                            BasePrice = 100.0m,
                            CategoryId = 9,
                            Code = "hoop_piercing",
                            Description = "Circular or semi-circular hoop for various piercing locations, with secure closure mechanism",
                            IsActive = true,
                            Name = "Hoop Piercing"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000003"),
                            BasePrice = 90.0m,
                            CategoryId = 9,
                            Code = "straight_barbell",
                            Description = "Straight bar with threaded balls or decorative ends on both sides, used for tongue, nipple, or industrial piercings",
                            IsActive = true,
                            Name = "Straight Barbell"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000004"),
                            BasePrice = 95.0m,
                            CategoryId = 9,
                            Code = "curved_barbell",
                            Description = "Gently curved bar with threaded ends, commonly used for eyebrow, navel, or rook piercings",
                            IsActive = true,
                            Name = "Curved Barbell"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            BasePrice = 80.0m,
                            CategoryId = 10,
                            Code = "single_stone_hair_pin",
                            Description = "Simple hair pin with a single gemstone or decorative element at the top",
                            IsActive = true,
                            Name = "Single Stone Hair Pin"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            BasePrice = 120.0m,
                            CategoryId = 10,
                            Code = "cluster_decorative_hair_pin",
                            Description = "Hair pin featuring a cluster of small stones or floral elements in an ornate design",
                            IsActive = true,
                            Name = "Cluster Decorative Hair Pin"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            BasePrice = 150.0m,
                            CategoryId = 10,
                            Code = "decorative_hair_comb",
                            Description = "Hair comb with decorative top edge embellished with stones or metal work",
                            IsActive = true,
                            Name = "Decorative Hair Comb"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            BasePrice = 60.0m,
                            CategoryId = 10,
                            Code = "minimal_bar_hair_clip",
                            Description = "Simple metal bar hair clip with clean lines and minimal decoration",
                            IsActive = true,
                            Name = "Minimal Bar Hair Clip"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            BasePrice = 500.0m,
                            CategoryId = 12,
                            Code = "mens_signet_ring",
                            Description = "Bold signet ring with wide band and large flat top surface, suitable for engraving or emblem",
                            IsActive = true,
                            Name = "Men's Signet Ring"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            BasePrice = 400.0m,
                            CategoryId = 12,
                            Code = "mens_chain_necklace",
                            Description = "Substantial chain necklace with heavier gauge links, masculine and durable design",
                            IsActive = true,
                            Name = "Men's Chain Necklace"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            BasePrice = 450.0m,
                            CategoryId = 12,
                            Code = "mens_link_bracelet",
                            Description = "Heavy link bracelet with robust construction and masculine proportions",
                            IsActive = true,
                            Name = "Men's Link Bracelet"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000004"),
                            BasePrice = 180.0m,
                            CategoryId = 12,
                            Code = "classic_cufflinks",
                            Description = "Pair of dress shirt cufflinks with simple geometric shape, suitable for formal wear",
                            IsActive = true,
                            Name = "Classic Cufflinks"
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000001"),
                            BasePrice = 150.0m,
                            CategoryId = 14,
                            Code = "plain_latin_cross",
                            Description = "Simple Latin cross with clean lines and smooth surface, traditional proportions with longer vertical beam",
                            IsActive = true,
                            Name = "Plain Latin Cross"
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000002"),
                            BasePrice = 180.0m,
                            CategoryId = 14,
                            Code = "orthodox_style_cross",
                            Description = "Three-bar cross design in Orthodox tradition, featuring slanted lower bar and detailed proportions",
                            IsActive = true,
                            Name = "Orthodox-Style Cross"
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000003"),
                            BasePrice = 280.0m,
                            CategoryId = 14,
                            Code = "cross_with_stones",
                            Description = "Latin cross embellished with small gemstones set along the beams or at intersection points",
                            IsActive = true,
                            Name = "Cross with Stones"
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000004"),
                            BasePrice = 120.0m,
                            CategoryId = 14,
                            Code = "minimal_thin_cross",
                            Description = "Delicate cross with very thin wire-like construction, modern and understated design",
                            IsActive = true,
                            Name = "Minimal Thin Cross"
                        });
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("JewelryCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "rings",
                            Description = "Engagement and decorative rings",
                            IsActive = true,
                            Name = "Rings"
                        },
                        new
                        {
                            Id = 2,
                            Code = "earrings",
                            Description = "Various types of earrings",
                            IsActive = true,
                            Name = "Earrings"
                        },
                        new
                        {
                            Id = 3,
                            Code = "pendants",
                            Description = "Pendants and charms",
                            IsActive = true,
                            Name = "Pendants"
                        },
                        new
                        {
                            Id = 4,
                            Code = "necklaces",
                            Description = "Statement and delicate necklaces",
                            IsActive = true,
                            Name = "Necklaces"
                        },
                        new
                        {
                            Id = 5,
                            Code = "bracelets",
                            Description = "Bangles and chain bracelets",
                            IsActive = true,
                            Name = "Bracelets"
                        },
                        new
                        {
                            Id = 6,
                            Code = "chains",
                            Description = "Necklace and bracelet chains",
                            IsActive = true,
                            Name = "Chains"
                        },
                        new
                        {
                            Id = 7,
                            Code = "brooches",
                            Description = "Decorative brooches and pins",
                            IsActive = true,
                            Name = "Brooches"
                        },
                        new
                        {
                            Id = 8,
                            Code = "cufflinks",
                            Description = "Cufflinks and tie accessories",
                            IsActive = false,
                            Name = "Cufflinks"
                        },
                        new
                        {
                            Id = 9,
                            Code = "piercing",
                            Description = "Body piercing jewelry",
                            IsActive = true,
                            Name = "Piercing"
                        },
                        new
                        {
                            Id = 10,
                            Code = "hair_jewelry",
                            Description = "Hair accessories and ornaments",
                            IsActive = true,
                            Name = "Hair jewelry"
                        },
                        new
                        {
                            Id = 11,
                            Code = "sets",
                            Description = "Matching jewelry sets",
                            IsActive = false,
                            Name = "Sets"
                        },
                        new
                        {
                            Id = 12,
                            Code = "mens_jewelry",
                            Description = "Jewelry designed for men",
                            IsActive = true,
                            Name = "Men's jewelry"
                        },
                        new
                        {
                            Id = 13,
                            Code = "custom",
                            Description = "Unique custom-made jewelry",
                            IsActive = false,
                            Name = "Custom Designs"
                        },
                        new
                        {
                            Id = 14,
                            Code = "cross_pendants",
                            Description = "Religious cross pendants and charms",
                            IsActive = true,
                            Name = "Cross pendants"
                        });
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EstimatedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BaseModelId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("UserId");

                    b.ToTable("JewelryConfigurations");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfigurationEngraving", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<string>("FontName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("SizeMm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("JewelryConfigurationEngravings");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfigurationStone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CaratWeight")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("PlacementDataJson")
                        .HasColumnType("text");

                    b.Property<int>("PositionIndex")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SizeMm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("StoneTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("StoneTypeId");

                    b.ToTable("JewelryConfigurationStones");
                });

            modelBuilder.Entity("JewerlyBack.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("Karat")
                        .HasColumnType("integer");

                    b.Property<string>("MetalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PriceFactor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "gold_14k_yellow",
                            ColorHex = "#FFD700",
                            IsActive = true,
                            Karat = 14,
                            MetalType = "gold",
                            Name = "14K Yellow Gold",
                            PriceFactor = 1.0m
                        },
                        new
                        {
                            Id = 2,
                            Code = "gold_18k_yellow",
                            ColorHex = "#FFDF00",
                            IsActive = true,
                            Karat = 18,
                            MetalType = "gold",
                            Name = "18K Yellow Gold",
                            PriceFactor = 1.2m
                        },
                        new
                        {
                            Id = 3,
                            Code = "gold_14k_white",
                            ColorHex = "#E5E4E2",
                            IsActive = true,
                            Karat = 14,
                            MetalType = "gold",
                            Name = "14K White Gold",
                            PriceFactor = 1.05m
                        },
                        new
                        {
                            Id = 4,
                            Code = "gold_18k_white",
                            ColorHex = "#E8E8E8",
                            IsActive = true,
                            Karat = 18,
                            MetalType = "gold",
                            Name = "18K White Gold",
                            PriceFactor = 1.25m
                        },
                        new
                        {
                            Id = 5,
                            Code = "gold_14k_rose",
                            ColorHex = "#B76E79",
                            IsActive = true,
                            Karat = 14,
                            MetalType = "gold",
                            Name = "14K Rose Gold",
                            PriceFactor = 1.05m
                        },
                        new
                        {
                            Id = 6,
                            Code = "gold_18k_rose",
                            ColorHex = "#C9A0A0",
                            IsActive = true,
                            Karat = 18,
                            MetalType = "gold",
                            Name = "18K Rose Gold",
                            PriceFactor = 1.25m
                        },
                        new
                        {
                            Id = 7,
                            Code = "platinum",
                            ColorHex = "#E5E4E2",
                            IsActive = true,
                            MetalType = "platinum",
                            Name = "Platinum",
                            PriceFactor = 1.4m
                        },
                        new
                        {
                            Id = 8,
                            Code = "silver_925",
                            ColorHex = "#C0C0C0",
                            IsActive = true,
                            MetalType = "silver",
                            Name = "Sterling Silver 925",
                            PriceFactor = 0.6m
                        },
                        new
                        {
                            Id = 9,
                            Code = "titanium",
                            ColorHex = "#878681",
                            IsActive = true,
                            MetalType = "titanium",
                            Name = "Titanium",
                            PriceFactor = 0.8m
                        });
                });

            modelBuilder.Entity("JewerlyBack.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("JewerlyBack.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ItemPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("JewerlyBack.Models.StoneType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("DefaultPricePerCarat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("StoneTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "diamond",
                            Color = "Clear",
                            DefaultPricePerCarat = 5000.0m,
                            IsActive = true,
                            Name = "Diamond"
                        },
                        new
                        {
                            Id = 2,
                            Code = "sapphire",
                            Color = "Blue",
                            DefaultPricePerCarat = 1500.0m,
                            IsActive = true,
                            Name = "Sapphire"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ruby",
                            Color = "Red",
                            DefaultPricePerCarat = 1800.0m,
                            IsActive = true,
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = 4,
                            Code = "emerald",
                            Color = "Green",
                            DefaultPricePerCarat = 2000.0m,
                            IsActive = true,
                            Name = "Emerald"
                        },
                        new
                        {
                            Id = 5,
                            Code = "moissanite",
                            Color = "Clear",
                            DefaultPricePerCarat = 400.0m,
                            IsActive = true,
                            Name = "Moissanite"
                        },
                        new
                        {
                            Id = 6,
                            Code = "topaz",
                            Color = "Blue",
                            DefaultPricePerCarat = 250.0m,
                            IsActive = true,
                            Name = "Topaz"
                        },
                        new
                        {
                            Id = 7,
                            Code = "amethyst",
                            Color = "Purple",
                            DefaultPricePerCarat = 150.0m,
                            IsActive = true,
                            Name = "Amethyst"
                        },
                        new
                        {
                            Id = 8,
                            Code = "citrine",
                            Color = "Yellow",
                            DefaultPricePerCarat = 180.0m,
                            IsActive = true,
                            Name = "Citrine"
                        },
                        new
                        {
                            Id = 9,
                            Code = "aquamarine",
                            Color = "Light Blue",
                            DefaultPricePerCarat = 300.0m,
                            IsActive = true,
                            Name = "Aquamarine"
                        },
                        new
                        {
                            Id = 10,
                            Code = "garnet",
                            Color = "Deep Red",
                            DefaultPricePerCarat = 200.0m,
                            IsActive = true,
                            Name = "Garnet"
                        });
                });

            modelBuilder.Entity("JewerlyBack.Models.UploadedAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("UserId");

                    b.ToTable("UploadedAssets");
                });

            modelBuilder.Entity("JewerlyBack.Models.AiPreviewJob", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryConfiguration", "Configuration")
                        .WithMany()
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryBaseModel", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryCategory", "Category")
                        .WithMany("BaseModels")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfiguration", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryBaseModel", "BaseModel")
                        .WithMany("Configurations")
                        .HasForeignKey("BaseModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JewerlyBack.Models.Material", "Material")
                        .WithMany("Configurations")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JewerlyBack.Models.AppUser", "User")
                        .WithMany("Configurations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseModel");

                    b.Navigation("Material");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfigurationEngraving", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryConfiguration", "Configuration")
                        .WithMany("Engravings")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfigurationStone", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryConfiguration", "Configuration")
                        .WithMany("Stones")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewerlyBack.Models.StoneType", "StoneType")
                        .WithMany("ConfigurationStones")
                        .HasForeignKey("StoneTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("StoneType");
                });

            modelBuilder.Entity("JewerlyBack.Models.Order", b =>
                {
                    b.HasOne("JewerlyBack.Models.AppUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JewerlyBack.Models.OrderItem", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryConfiguration", "Configuration")
                        .WithMany("OrderItems")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JewerlyBack.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("JewerlyBack.Models.UploadedAsset", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryConfiguration", "Configuration")
                        .WithMany("Assets")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JewerlyBack.Models.AppUser", "User")
                        .WithMany("Assets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JewerlyBack.Models.AppUser", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Configurations");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryBaseModel", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryCategory", b =>
                {
                    b.Navigation("BaseModels");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfiguration", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Engravings");

                    b.Navigation("OrderItems");

                    b.Navigation("Stones");
                });

            modelBuilder.Entity("JewerlyBack.Models.Material", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("JewerlyBack.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("JewerlyBack.Models.StoneType", b =>
                {
                    b.Navigation("ConfigurationStones");
                });
#pragma warning restore 612, 618
        }
    }
}
