// <auto-generated />
using System;
using JewerlyBack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JewerlyBack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251206170013_MakeUserIdNullableInJewelryConfiguration")]
    partial class MakeUserIdNullableInJewelryConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JewerlyBack.Models.AiPreviewJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FramesJson")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("GuestClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prompt")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("SingleImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("Status");

                    b.HasIndex("GuestClientId", "Status")
                        .HasFilter("\"GuestClientId\" IS NOT NULL");

                    b.ToTable("AiPreviewJobs");
                });

            modelBuilder.Entity("JewerlyBack.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Provider", "ExternalId")
                        .HasFilter("\"Provider\" IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryBaseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PreviewImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("JewelryBaseModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            BasePrice = 500.0m,
                            CategoryId = 1,
                            Code = "ring_solitaire_classic",
                            Description = "Elegant thin band with a single center stone in prong setting",
                            IsActive = true,
                            MetadataJson = "{\"defaultRingSize\":16.5,\"bandWidth\":2.0}",
                            Name = "Classic Solitaire Ring"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            BasePrice = 800.0m,
                            CategoryId = 1,
                            Code = "ring_engagement_halo",
                            Description = "Center stone surrounded by a halo of smaller accent stones",
                            IsActive = true,
                            MetadataJson = "{\"defaultRingSize\":16.5,\"bandWidth\":2.5}",
                            Name = "Halo Engagement Ring"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            BasePrice = 400.0m,
                            CategoryId = 1,
                            Code = "ring_wide_band",
                            Description = "Modern wide band with smooth polished surface",
                            IsActive = true,
                            MetadataJson = "{\"defaultRingSize\":17.0,\"bandWidth\":5.0}",
                            Name = "Wide Band Ring"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            BasePrice = 300.0m,
                            CategoryId = 2,
                            Code = "earring_stud_classic",
                            Description = "Minimalist studs with a single gemstone",
                            IsActive = true,
                            MetadataJson = "{\"stoneSize\":5.0}",
                            Name = "Classic Stud Earrings"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            BasePrice = 250.0m,
                            CategoryId = 2,
                            Code = "earring_hoop_medium",
                            Description = "Classic round hoops, medium size",
                            IsActive = true,
                            MetadataJson = "{\"diameter\":25.0}",
                            Name = "Medium Hoop Earrings"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            BasePrice = 450.0m,
                            CategoryId = 2,
                            Code = "earring_drop_elegant",
                            Description = "Graceful drop earrings with dangling gemstone",
                            IsActive = true,
                            MetadataJson = "{\"length\":35.0}",
                            Name = "Elegant Drop Earrings"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            BasePrice = 200.0m,
                            CategoryId = 3,
                            Code = "pendant_round_simple",
                            Description = "Simple round pendant with center stone",
                            IsActive = true,
                            MetadataJson = "{\"diameter\":15.0}",
                            Name = "Round Pendant"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            BasePrice = 220.0m,
                            CategoryId = 3,
                            Code = "pendant_heart_classic",
                            Description = "Classic heart-shaped pendant",
                            IsActive = true,
                            MetadataJson = "{\"width\":12.0,\"height\":12.0}",
                            Name = "Heart Pendant"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            BasePrice = 280.0m,
                            CategoryId = 3,
                            Code = "pendant_solitaire",
                            Description = "Single stone pendant in prong setting",
                            IsActive = true,
                            MetadataJson = "{\"stoneSize\":6.0}",
                            Name = "Solitaire Pendant"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            BasePrice = 350.0m,
                            CategoryId = 4,
                            Code = "necklace_cable_chain",
                            Description = "Classic cable chain necklace",
                            IsActive = true,
                            MetadataJson = "{\"length\":45.0,\"linkSize\":3.0}",
                            Name = "Cable Chain Necklace"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            BasePrice = 180.0m,
                            CategoryId = 4,
                            Code = "necklace_pendant_base",
                            Description = "Delicate chain designed for pendants",
                            IsActive = true,
                            MetadataJson = "{\"length\":42.0,\"linkSize\":2.0}",
                            Name = "Pendant Necklace Base"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            BasePrice = 280.0m,
                            CategoryId = 5,
                            Code = "bracelet_chain_classic",
                            Description = "Simple elegant chain bracelet",
                            IsActive = true,
                            MetadataJson = "{\"length\":18.0,\"linkSize\":3.0}",
                            Name = "Classic Chain Bracelet"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            BasePrice = 320.0m,
                            CategoryId = 5,
                            Code = "bracelet_bangle_simple",
                            Description = "Smooth round bangle bracelet",
                            IsActive = true,
                            MetadataJson = "{\"diameter\":65.0,\"width\":4.0}",
                            Name = "Simple Bangle Bracelet"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            BasePrice = 950.0m,
                            CategoryId = 5,
                            Code = "bracelet_tennis",
                            Description = "Classic tennis bracelet with line of stones",
                            IsActive = true,
                            MetadataJson = "{\"length\":18.0,\"stoneCount\":20}",
                            Name = "Tennis Bracelet"
                        });
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("JewelryCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "rings",
                            Description = "Engagement and decorative rings",
                            IsActive = true,
                            Name = "Rings"
                        },
                        new
                        {
                            Id = 2,
                            Code = "earrings",
                            Description = "Various types of earrings",
                            IsActive = true,
                            Name = "Earrings"
                        },
                        new
                        {
                            Id = 3,
                            Code = "pendants",
                            Description = "Pendants and charms",
                            IsActive = true,
                            Name = "Pendants"
                        },
                        new
                        {
                            Id = 4,
                            Code = "necklaces",
                            Description = "Statement and delicate necklaces",
                            IsActive = true,
                            Name = "Necklaces"
                        },
                        new
                        {
                            Id = 5,
                            Code = "bracelets",
                            Description = "Bangles and chain bracelets",
                            IsActive = true,
                            Name = "Bracelets"
                        },
                        new
                        {
                            Id = 6,
                            Code = "chains",
                            Description = "Necklace and bracelet chains",
                            IsActive = true,
                            Name = "Chains"
                        },
                        new
                        {
                            Id = 7,
                            Code = "brooches",
                            Description = "Decorative brooches and pins",
                            IsActive = true,
                            Name = "Brooches"
                        },
                        new
                        {
                            Id = 8,
                            Code = "cufflinks",
                            Description = "Cufflinks and tie accessories",
                            IsActive = true,
                            Name = "Cufflinks"
                        },
                        new
                        {
                            Id = 9,
                            Code = "piercing",
                            Description = "Body piercing jewelry",
                            IsActive = true,
                            Name = "Piercing"
                        },
                        new
                        {
                            Id = 10,
                            Code = "hair_jewelry",
                            Description = "Hair accessories and ornaments",
                            IsActive = true,
                            Name = "Hair Jewelry"
                        },
                        new
                        {
                            Id = 11,
                            Code = "sets",
                            Description = "Matching jewelry sets",
                            IsActive = true,
                            Name = "Sets"
                        },
                        new
                        {
                            Id = 12,
                            Code = "mens_jewelry",
                            Description = "Jewelry designed for men",
                            IsActive = true,
                            Name = "Men's Jewelry"
                        },
                        new
                        {
                            Id = 13,
                            Code = "custom",
                            Description = "Unique custom-made jewelry",
                            IsActive = true,
                            Name = "Custom Designs"
                        });
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EstimatedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BaseModelId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("UserId");

                    b.ToTable("JewelryConfigurations");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfigurationEngraving", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<string>("FontName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("SizeMm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("JewelryConfigurationEngravings");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfigurationStone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CaratWeight")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("PlacementDataJson")
                        .HasColumnType("text");

                    b.Property<int>("PositionIndex")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SizeMm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("StoneTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("StoneTypeId");

                    b.ToTable("JewelryConfigurationStones");
                });

            modelBuilder.Entity("JewerlyBack.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("Karat")
                        .HasColumnType("integer");

                    b.Property<string>("MetalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PriceFactor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "gold_14k_yellow",
                            ColorHex = "#FFD700",
                            IsActive = true,
                            Karat = 14,
                            MetalType = "gold",
                            Name = "14K Yellow Gold",
                            PriceFactor = 1.0m
                        },
                        new
                        {
                            Id = 2,
                            Code = "gold_18k_yellow",
                            ColorHex = "#FFDF00",
                            IsActive = true,
                            Karat = 18,
                            MetalType = "gold",
                            Name = "18K Yellow Gold",
                            PriceFactor = 1.2m
                        },
                        new
                        {
                            Id = 3,
                            Code = "gold_14k_white",
                            ColorHex = "#E5E4E2",
                            IsActive = true,
                            Karat = 14,
                            MetalType = "gold",
                            Name = "14K White Gold",
                            PriceFactor = 1.05m
                        },
                        new
                        {
                            Id = 4,
                            Code = "gold_18k_white",
                            ColorHex = "#E8E8E8",
                            IsActive = true,
                            Karat = 18,
                            MetalType = "gold",
                            Name = "18K White Gold",
                            PriceFactor = 1.25m
                        },
                        new
                        {
                            Id = 5,
                            Code = "gold_14k_rose",
                            ColorHex = "#B76E79",
                            IsActive = true,
                            Karat = 14,
                            MetalType = "gold",
                            Name = "14K Rose Gold",
                            PriceFactor = 1.05m
                        },
                        new
                        {
                            Id = 6,
                            Code = "gold_18k_rose",
                            ColorHex = "#C9A0A0",
                            IsActive = true,
                            Karat = 18,
                            MetalType = "gold",
                            Name = "18K Rose Gold",
                            PriceFactor = 1.25m
                        },
                        new
                        {
                            Id = 7,
                            Code = "platinum",
                            ColorHex = "#E5E4E2",
                            IsActive = true,
                            MetalType = "platinum",
                            Name = "Platinum",
                            PriceFactor = 1.4m
                        },
                        new
                        {
                            Id = 8,
                            Code = "silver_925",
                            ColorHex = "#C0C0C0",
                            IsActive = true,
                            MetalType = "silver",
                            Name = "Sterling Silver 925",
                            PriceFactor = 0.6m
                        },
                        new
                        {
                            Id = 9,
                            Code = "titanium",
                            ColorHex = "#878681",
                            IsActive = true,
                            MetalType = "titanium",
                            Name = "Titanium",
                            PriceFactor = 0.8m
                        });
                });

            modelBuilder.Entity("JewerlyBack.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("JewerlyBack.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ItemPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("JewerlyBack.Models.StoneType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("DefaultPricePerCarat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("StoneTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "diamond",
                            Color = "Clear",
                            DefaultPricePerCarat = 5000.0m,
                            IsActive = true,
                            Name = "Diamond"
                        },
                        new
                        {
                            Id = 2,
                            Code = "sapphire",
                            Color = "Blue",
                            DefaultPricePerCarat = 1500.0m,
                            IsActive = true,
                            Name = "Sapphire"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ruby",
                            Color = "Red",
                            DefaultPricePerCarat = 1800.0m,
                            IsActive = true,
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = 4,
                            Code = "emerald",
                            Color = "Green",
                            DefaultPricePerCarat = 2000.0m,
                            IsActive = true,
                            Name = "Emerald"
                        },
                        new
                        {
                            Id = 5,
                            Code = "moissanite",
                            Color = "Clear",
                            DefaultPricePerCarat = 400.0m,
                            IsActive = true,
                            Name = "Moissanite"
                        },
                        new
                        {
                            Id = 6,
                            Code = "topaz",
                            Color = "Blue",
                            DefaultPricePerCarat = 250.0m,
                            IsActive = true,
                            Name = "Topaz"
                        },
                        new
                        {
                            Id = 7,
                            Code = "amethyst",
                            Color = "Purple",
                            DefaultPricePerCarat = 150.0m,
                            IsActive = true,
                            Name = "Amethyst"
                        },
                        new
                        {
                            Id = 8,
                            Code = "citrine",
                            Color = "Yellow",
                            DefaultPricePerCarat = 180.0m,
                            IsActive = true,
                            Name = "Citrine"
                        },
                        new
                        {
                            Id = 9,
                            Code = "aquamarine",
                            Color = "Light Blue",
                            DefaultPricePerCarat = 300.0m,
                            IsActive = true,
                            Name = "Aquamarine"
                        },
                        new
                        {
                            Id = 10,
                            Code = "garnet",
                            Color = "Deep Red",
                            DefaultPricePerCarat = 200.0m,
                            IsActive = true,
                            Name = "Garnet"
                        });
                });

            modelBuilder.Entity("JewerlyBack.Models.UploadedAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("UserId");

                    b.ToTable("UploadedAssets");
                });

            modelBuilder.Entity("JewerlyBack.Models.AiPreviewJob", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryConfiguration", "Configuration")
                        .WithMany()
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryBaseModel", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryCategory", "Category")
                        .WithMany("BaseModels")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfiguration", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryBaseModel", "BaseModel")
                        .WithMany("Configurations")
                        .HasForeignKey("BaseModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JewerlyBack.Models.Material", "Material")
                        .WithMany("Configurations")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JewerlyBack.Models.AppUser", "User")
                        .WithMany("Configurations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseModel");

                    b.Navigation("Material");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfigurationEngraving", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryConfiguration", "Configuration")
                        .WithMany("Engravings")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfigurationStone", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryConfiguration", "Configuration")
                        .WithMany("Stones")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewerlyBack.Models.StoneType", "StoneType")
                        .WithMany("ConfigurationStones")
                        .HasForeignKey("StoneTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("StoneType");
                });

            modelBuilder.Entity("JewerlyBack.Models.Order", b =>
                {
                    b.HasOne("JewerlyBack.Models.AppUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JewerlyBack.Models.OrderItem", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryConfiguration", "Configuration")
                        .WithMany("OrderItems")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JewerlyBack.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("JewerlyBack.Models.UploadedAsset", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryConfiguration", "Configuration")
                        .WithMany("Assets")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JewerlyBack.Models.AppUser", "User")
                        .WithMany("Assets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JewerlyBack.Models.AppUser", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Configurations");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryBaseModel", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryCategory", b =>
                {
                    b.Navigation("BaseModels");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfiguration", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Engravings");

                    b.Navigation("OrderItems");

                    b.Navigation("Stones");
                });

            modelBuilder.Entity("JewerlyBack.Models.Material", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("JewerlyBack.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("JewerlyBack.Models.StoneType", b =>
                {
                    b.Navigation("ConfigurationStones");
                });
#pragma warning restore 612, 618
        }
    }
}
