// <auto-generated />
using System;
using JewerlyBack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JewerlyBack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251209225618_AddAuditLogTable")]
    partial class AddAuditLogTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JewerlyBack.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Changes")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AuditLogs_UserId");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_EntityType_EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("JewerlyBack.Models.AiPreviewJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiConfigJson")
                        .HasColumnType("text");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FramesJson")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("GuestClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prompt")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("SingleImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("Status");

                    b.HasIndex("GuestClientId", "Status")
                        .HasFilter("\"GuestClientId\" IS NOT NULL");

                    b.ToTable("AiPreviewJobs");
                });

            modelBuilder.Entity("JewerlyBack.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Provider", "ExternalId")
                        .HasFilter("\"Provider\" IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryBaseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiDescription")
                        .HasColumnType("text");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PreviewImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("JewelryBaseModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            AiDescription = "A classic solid band ring with a smooth, even surface and medium width, without any stones or engravings. The profile is gently rounded for everyday wear.",
                            BasePrice = 250.0m,
                            CategoryId = 1,
                            Code = "classic_solid_band",
                            Description = "Simple solid metal band with smooth polished surface, uniform width throughout",
                            IsActive = true,
                            Name = "Classic Solid Band"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            AiDescription = "A delicate thin band ring with a single round stone set at the top in a simple prong or bezel setting, emphasizing minimalism and lightness.",
                            BasePrice = 400.0m,
                            CategoryId = 1,
                            Code = "thin_band_single_stone",
                            Description = "Delicate thin band featuring one small stone set in a minimal prong or bezel setting",
                            IsActive = true,
                            Name = "Thin Band with Single Stone"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            AiDescription = "An engagement ring with a raised central setting holding a single larger stone, with a clean, elegant band that draws attention to the solitaire.",
                            BasePrice = 800.0m,
                            CategoryId = 1,
                            Code = "solitaire_engagement_ring",
                            Description = "Classic engagement ring with a prominent center stone elevated in a four or six-prong setting on a slender band",
                            IsActive = true,
                            Name = "Solitaire Engagement Ring"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            AiDescription = "A narrow ring with a continuous line of evenly spaced small stones going all the way around the band, creating a uniform sparkle from every angle.",
                            BasePrice = 950.0m,
                            CategoryId = 1,
                            Code = "eternity_ring",
                            Description = "Band fully encircled with small identical stones set side-by-side in a continuous channel or prong setting",
                            IsActive = true,
                            Name = "Eternity Ring"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            AiDescription = "A solid, slightly heavier ring with a flat or gently curved top surface intended for a symbol or engraving, with a strong, masculine silhouette.",
                            BasePrice = 450.0m,
                            CategoryId = 1,
                            Code = "signet_ring",
                            Description = "Broad band with a flat rectangular or oval top surface suitable for engraving or decorative elements",
                            IsActive = true,
                            Name = "Signet Ring"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            AiDescription = "A small stud earring with a single stone or smooth disc sitting close to the earlobe, mounted on a straight post with a simple backing.",
                            BasePrice = 300.0m,
                            CategoryId = 2,
                            Code = "classic_stud",
                            Description = "Simple stud earring with a single gemstone set directly on a post, minimalist and close to the earlobe",
                            IsActive = true,
                            Name = "Classic Stud"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            AiDescription = "A stud earring formed by a tight cluster of several small stones or elements arranged into a compact shape that sits on the earlobe.",
                            BasePrice = 450.0m,
                            CategoryId = 2,
                            Code = "cluster_stud",
                            Description = "Stud earring featuring multiple small stones arranged in a tight cluster around a central stone",
                            IsActive = true,
                            Name = "Cluster Stud"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            AiDescription = "A small, smooth hoop earring that hugs the earlobe closely, with a continuous circular or slightly oval shape and no additional stones.",
                            BasePrice = 220.0m,
                            CategoryId = 2,
                            Code = "small_hoop",
                            Description = "Smooth metal hoop in a small diameter, simple circular shape that hugs the earlobe",
                            IsActive = true,
                            Name = "Small Hoop"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            AiDescription = "A medium-sized hoop earring with stones set along the visible outer front section of the hoop, combining a clean circular form with a line of sparkle.",
                            BasePrice = 550.0m,
                            CategoryId = 2,
                            Code = "hoop_with_stones",
                            Description = "Hoop earring with small stones set along the outer edge, adding sparkle to the classic hoop design",
                            IsActive = true,
                            Name = "Hoop with Stones"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            AiDescription = "A minimalist drop earring where a small pendant element hangs from a short connector, creating a light movement just below the earlobe.",
                            BasePrice = 380.0m,
                            CategoryId = 2,
                            Code = "simple_drop_earring",
                            Description = "Earring with a single stone or element suspended below the earlobe on a short chain or wire",
                            IsActive = true,
                            Name = "Simple Drop Earring"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            AiDescription = "A flat round disc pendant with a polished surface and a small bail at the top, ideal for engraving or subtle minimalist styling.",
                            BasePrice = 180.0m,
                            CategoryId = 3,
                            Code = "round_disc_pendant",
                            Description = "Flat circular disc pendant with smooth surface, ideal for engraving or minimal embellishment",
                            IsActive = true,
                            Name = "Round Disc Pendant"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            AiDescription = "A narrow vertical bar pendant with clean straight edges and a slim rectangular shape, hanging from a small bail for a modern look.",
                            BasePrice = 200.0m,
                            CategoryId = 3,
                            Code = "bar_pendant_vertical",
                            Description = "Slender vertical bar pendant with clean lines and modern aesthetic, suspended by the top edge",
                            IsActive = true,
                            Name = "Bar Pendant (Vertical)"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            AiDescription = "A pendant in the shape of a heart outline with open center, made from a smooth metal contour that feels light and romantic.",
                            BasePrice = 220.0m,
                            CategoryId = 3,
                            Code = "heart_outline_pendant",
                            Description = "Open heart shape formed by a thin metal outline, romantic and delicate design",
                            IsActive = true,
                            Name = "Heart Outline Pendant"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            AiDescription = "A pendant built around a single central stone in a delicate setting, suspended from a small bail so the stone becomes the main focus.",
                            BasePrice = 350.0m,
                            CategoryId = 3,
                            Code = "single_stone_pendant",
                            Description = "Single prominent gemstone held in a prong or bezel setting, suspended from a chain as the focal point",
                            IsActive = true,
                            Name = "Single Stone Pendant"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            AiDescription = "A simple open circle pendant with a smooth round contour and empty center, symbolizing continuity and minimalism.",
                            BasePrice = 190.0m,
                            CategoryId = 3,
                            Code = "open_circle_pendant",
                            Description = "Circular ring pendant with open center, representing continuity and eternity",
                            IsActive = true,
                            Name = "Open Circle Pendant"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            AiDescription = "A fine chain necklace with a single small pendant fixed in the center so it always rests at the front of the neck.",
                            BasePrice = 280.0m,
                            CategoryId = 4,
                            Code = "chain_small_central_pendant",
                            Description = "Delicate chain with a small decorative pendant or charm positioned at the center front",
                            IsActive = true,
                            Name = "Chain with Small Central Pendant"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            AiDescription = "A continuous line necklace made of closely set stones of similar size, forming a flexible sparkling band around the neck.",
                            BasePrice = 1200.0m,
                            CategoryId = 4,
                            Code = "tennis_necklace",
                            Description = "Continuous line of identical stones set in individual settings, creating a sparkling collar effect",
                            IsActive = true,
                            Name = "Tennis Necklace"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            AiDescription = "A short, close-fitting necklace that sits high on the neck, designed as a smooth, minimal band without large dangling elements.",
                            BasePrice = 220.0m,
                            CategoryId = 4,
                            Code = "minimal_choker_band",
                            Description = "Simple thin metal band that sits snugly around the neck, modern and streamlined",
                            IsActive = true,
                            Name = "Minimal Choker Band"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            AiDescription = "A necklace with a horizontal plate or word element at the center of a fine chain, suitable for names or short inscriptions.",
                            BasePrice = 250.0m,
                            CategoryId = 4,
                            Code = "name_plate_necklace",
                            Description = "Horizontal rectangular plate attached to a chain, designed for personalized name or word engraving",
                            IsActive = true,
                            Name = "Name Plate Necklace"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            AiDescription = "A classic chain bracelet composed of repeating metal links, flexible and lightweight, closing with a simple clasp.",
                            BasePrice = 280.0m,
                            CategoryId = 5,
                            Code = "chain_bracelet",
                            Description = "Flexible linked chain bracelet with clasp closure, elegant and adjustable",
                            IsActive = true,
                            Name = "Chain Bracelet"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            AiDescription = "A rigid bangle bracelet formed as a closed or nearly closed ring, with a smooth exterior surface and consistent thickness.",
                            BasePrice = 320.0m,
                            CategoryId = 5,
                            Code = "solid_bangle",
                            Description = "Rigid circular bracelet in solid metal, slips over the hand without a clasp",
                            IsActive = true,
                            Name = "Solid Bangle"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            AiDescription = "A bracelet made of a single row of evenly spaced stones set closely together, creating a continuous line of sparkle around the wrist.",
                            BasePrice = 950.0m,
                            CategoryId = 5,
                            Code = "tennis_bracelet",
                            Description = "Line bracelet with a continuous row of individually set stones linked together",
                            IsActive = true,
                            Name = "Tennis Bracelet"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            AiDescription = "A bracelet with a series of small pendants or charms attached to a base chain, allowing multiple decorative elements to dangle.",
                            BasePrice = 300.0m,
                            CategoryId = 5,
                            Code = "charm_bracelet",
                            Description = "Chain bracelet with attachment points for hanging decorative charms or pendants",
                            IsActive = true,
                            Name = "Charm Bracelet"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            AiDescription = "A simple cable chain made from uniform round or oval links connected in a straightforward pattern, suitable for pendants or standalone wear.",
                            BasePrice = 150.0m,
                            CategoryId = 6,
                            Code = "cable_chain",
                            Description = "Classic chain with uniform oval or round links connected in a simple alternating pattern",
                            IsActive = true,
                            Name = "Cable Chain"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            AiDescription = "A curb chain with flattened, twisted links that lie smoothly against the skin, giving a slightly heavier and more masculine look.",
                            BasePrice = 170.0m,
                            CategoryId = 6,
                            Code = "curb_chain",
                            Description = "Chain with interlocking uniform links that lie flat when worn, creating a smooth surface",
                            IsActive = true,
                            Name = "Curb Chain"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            AiDescription = "A Figaro chain with a repeating pattern of one or two shorter links followed by a longer link, creating a rhythmic, stylish structure.",
                            BasePrice = 160.0m,
                            CategoryId = 6,
                            Code = "figaro_chain",
                            Description = "Chain with alternating pattern of short and long oval links, typically three short links followed by one elongated link",
                            IsActive = true,
                            Name = "Figaro Chain"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000004"),
                            AiDescription = "A rope chain built from twisted links that visually mimic a rope, with a textured, three-dimensional appearance and continuous spiral look.",
                            BasePrice = 200.0m,
                            CategoryId = 6,
                            Code = "rope_chain",
                            Description = "Chain with small links twisted together to resemble rope texture, creating a thick and durable design",
                            IsActive = true,
                            Name = "Rope Chain"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000005"),
                            AiDescription = "A chain composed of small square or box-shaped links, forming a strong, geometric and slightly more structured profile.",
                            BasePrice = 180.0m,
                            CategoryId = 6,
                            Code = "box_chain",
                            Description = "Chain with square links forming a smooth, continuous tube-like appearance",
                            IsActive = true,
                            Name = "Box Chain"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            AiDescription = "A brooch shaped like a stylized flower with petals radiating from the center, designed to sit flat on fabric and add a decorative accent.",
                            BasePrice = 280.0m,
                            CategoryId = 7,
                            Code = "floral_brooch",
                            Description = "Decorative pin with flower-inspired design featuring petals and possibly a center stone",
                            IsActive = true,
                            Name = "Floral Brooch"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            AiDescription = "An elongated bar-shaped brooch with clean geometric lines, often worn horizontally or diagonally as a subtle modern statement.",
                            BasePrice = 220.0m,
                            CategoryId = 7,
                            Code = "geometric_bar_brooch",
                            Description = "Horizontal bar pin with clean geometric lines and modern aesthetic",
                            IsActive = true,
                            Name = "Geometric Bar Brooch"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000003"),
                            AiDescription = "A brooch representing the silhouette or detailed figure of an animal, with contours and details emphasizing its character.",
                            BasePrice = 300.0m,
                            CategoryId = 7,
                            Code = "animal_shape_brooch",
                            Description = "Decorative pin shaped like an animal or creature, often embellished with stones or enamel",
                            IsActive = true,
                            Name = "Animal Shape Brooch"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000004"),
                            AiDescription = "A brooch based on one or more letters intertwined into a decorative monogram, designed to stand out on clothing with refined lines.",
                            BasePrice = 250.0m,
                            CategoryId = 7,
                            Code = "monogram_brooch",
                            Description = "Pin featuring stylized initials or letters in an elegant font design",
                            IsActive = true,
                            Name = "Monogram Brooch"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000001"),
                            AiDescription = "A piercing jewelry piece with a flat disc on one end and a decorative top on the other, designed to sit flush against the skin.",
                            BasePrice = 120.0m,
                            CategoryId = 9,
                            Code = "labret_stud",
                            Description = "Flat-back piercing stud with decorative front, suitable for lip, ear cartilage, or other piercings",
                            IsActive = true,
                            Name = "Labret Stud"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000002"),
                            AiDescription = "A small, smooth hoop for piercing that forms a mostly closed circle, suitable for ears, nose, or other placements.",
                            BasePrice = 100.0m,
                            CategoryId = 9,
                            Code = "hoop_piercing",
                            Description = "Circular or semi-circular hoop for various piercing locations, with secure closure mechanism",
                            IsActive = true,
                            Name = "Hoop Piercing"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000003"),
                            AiDescription = "A straight bar piercing with a central shaft and a removable ball or decorative element on each end, used for tongue or ear piercings.",
                            BasePrice = 90.0m,
                            CategoryId = 9,
                            Code = "straight_barbell",
                            Description = "Straight bar with threaded balls or decorative ends on both sides, used for tongue, nipple, or industrial piercings",
                            IsActive = true,
                            Name = "Straight Barbell"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000004"),
                            AiDescription = "A gently curved barbell with beads or decorative ends, intended for areas like the eyebrow or navel where the curve follows the body.",
                            BasePrice = 95.0m,
                            CategoryId = 9,
                            Code = "curved_barbell",
                            Description = "Gently curved bar with threaded ends, commonly used for eyebrow, navel, or rook piercings",
                            IsActive = true,
                            Name = "Curved Barbell"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            AiDescription = "A slim hair pin with a single stone or decorative element mounted at one end, meant to be partially visible in the hairstyle.",
                            BasePrice = 80.0m,
                            CategoryId = 10,
                            Code = "single_stone_hair_pin",
                            Description = "Simple hair pin with a single gemstone or decorative element at the top",
                            IsActive = true,
                            Name = "Single Stone Hair Pin"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            AiDescription = "A hair pin with a small cluster of stones or elements arranged near the tip, creating a more pronounced decorative accent in the hair.",
                            BasePrice = 120.0m,
                            CategoryId = 10,
                            Code = "cluster_decorative_hair_pin",
                            Description = "Hair pin featuring a cluster of small stones or floral elements in an ornate design",
                            IsActive = true,
                            Name = "Cluster Decorative Hair Pin"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            AiDescription = "A short comb with multiple teeth that slide into the hair and a decorative top bar featuring stones or metal motifs.",
                            BasePrice = 150.0m,
                            CategoryId = 10,
                            Code = "decorative_hair_comb",
                            Description = "Hair comb with decorative top edge embellished with stones or metal work",
                            IsActive = true,
                            Name = "Decorative Hair Comb"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            AiDescription = "A sleek bar-style hair clip with a clean rectangular front piece, designed to hold a section of hair with minimal visual clutter.",
                            BasePrice = 60.0m,
                            CategoryId = 10,
                            Code = "minimal_bar_hair_clip",
                            Description = "Simple metal bar hair clip with clean lines and minimal decoration",
                            IsActive = true,
                            Name = "Minimal Bar Hair Clip"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            AiDescription = "A substantial men's signet ring with a flat or lightly domed top face and thicker band, designed for a bold, classic masculine statement.",
                            BasePrice = 500.0m,
                            CategoryId = 12,
                            Code = "mens_signet_ring",
                            Description = "Bold signet ring with wide band and large flat top surface, suitable for engraving or emblem",
                            IsActive = true,
                            Name = "Men's Signet Ring"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            AiDescription = "A medium-thickness chain necklace with sturdy links and a slightly heavier feel, intended for men's everyday wear.",
                            BasePrice = 400.0m,
                            CategoryId = 12,
                            Code = "mens_chain_necklace",
                            Description = "Substantial chain necklace with heavier gauge links, masculine and durable design",
                            IsActive = true,
                            Name = "Men's Chain Necklace"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            AiDescription = "A bracelet made of larger, stronger links that form a solid masculine chain around the wrist, closing with a robust clasp.",
                            BasePrice = 450.0m,
                            CategoryId = 12,
                            Code = "mens_link_bracelet",
                            Description = "Heavy link bracelet with robust construction and masculine proportions",
                            IsActive = true,
                            Name = "Men's Link Bracelet"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000004"),
                            AiDescription = "A pair of classic cufflinks with a flat or slightly domed decorative front face and a hinged back part that secures the cuff.",
                            BasePrice = 180.0m,
                            CategoryId = 12,
                            Code = "classic_cufflinks",
                            Description = "Pair of dress shirt cufflinks with simple geometric shape, suitable for formal wear",
                            IsActive = true,
                            Name = "Classic Cufflinks"
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000001"),
                            AiDescription = "A simple Latin cross pendant with clean straight arms and a slightly elongated vertical bar, without stones or engravings.",
                            BasePrice = 150.0m,
                            CategoryId = 14,
                            Code = "plain_latin_cross",
                            Description = "Simple Latin cross with clean lines and smooth surface, traditional proportions with longer vertical beam",
                            IsActive = true,
                            Name = "Plain Latin Cross"
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000002"),
                            AiDescription = "A pendant in an Orthodox-style cross shape with characteristic additional crossbars and more intricate contours.",
                            BasePrice = 180.0m,
                            CategoryId = 14,
                            Code = "orthodox_style_cross",
                            Description = "Three-bar cross design in Orthodox tradition, featuring slanted lower bar and detailed proportions",
                            IsActive = true,
                            Name = "Orthodox-Style Cross"
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000003"),
                            AiDescription = "A cross pendant with small stones set along the arms, adding sparkle while preserving the clear cross silhouette.",
                            BasePrice = 280.0m,
                            CategoryId = 14,
                            Code = "cross_with_stones",
                            Description = "Latin cross embellished with small gemstones set along the beams or at intersection points",
                            IsActive = true,
                            Name = "Cross with Stones"
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000004"),
                            AiDescription = "A very slim, minimal cross pendant with narrow arms and a lightweight appearance, emphasizing simplicity and elegance.",
                            BasePrice = 120.0m,
                            CategoryId = 14,
                            Code = "minimal_thin_cross",
                            Description = "Delicate cross with very thin wire-like construction, modern and understated design",
                            IsActive = true,
                            Name = "Minimal Thin Cross"
                        });
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiCategoryDescription")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("JewelryCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AiCategoryDescription = "A ring is a circular band worn on the finger, ranging from simple bands to elaborate designs with stones. Rings can be engagement rings with prominent center stones, wedding bands, fashion rings, or signet rings. They are designed to encircle the finger smoothly and can feature various widths, profiles, and decorative elements.",
                            Code = "rings",
                            Description = "Engagement and decorative rings",
                            IsActive = true,
                            Name = "Rings"
                        },
                        new
                        {
                            Id = 2,
                            AiCategoryDescription = "Earrings are jewelry pieces worn on or hanging from the earlobe or ear cartilage. They include studs that sit close to the ear, hoops that form circular shapes, drop earrings that dangle below the lobe, and more elaborate chandelier styles. Earrings are typically sold and worn as matching pairs.",
                            Code = "earrings",
                            Description = "Various types of earrings",
                            IsActive = true,
                            Name = "Earrings"
                        },
                        new
                        {
                            Id = 3,
                            AiCategoryDescription = "A pendant is a decorative element designed to hang from a chain or cord around the neck. Pendants can be geometric shapes, symbols, stones in settings, or representational forms. They typically feature a bail or loop at the top for attachment and serve as the focal point of a necklace.",
                            Code = "pendants",
                            Description = "Pendants and charms",
                            IsActive = true,
                            Name = "Pendants"
                        },
                        new
                        {
                            Id = 4,
                            AiCategoryDescription = "A necklace is a complete piece of jewelry that encircles the neck, including both the chain or structure and any decorative elements. Necklaces can be simple chains, tennis necklaces with continuous stones, chokers that sit high on the neck, or statement pieces with integrated pendants or decorative sections.",
                            Code = "necklaces",
                            Description = "Statement and delicate necklaces",
                            IsActive = true,
                            Name = "Necklaces"
                        },
                        new
                        {
                            Id = 5,
                            AiCategoryDescription = "A bracelet is jewelry worn around the wrist, either as a flexible chain with a clasp or as a rigid bangle that slips over the hand. Bracelets can be delicate chains, tennis bracelets with continuous stones, charm bracelets with dangling elements, or solid cuffs and bangles.",
                            Code = "bracelets",
                            Description = "Bangles and chain bracelets",
                            IsActive = true,
                            Name = "Bracelets"
                        },
                        new
                        {
                            Id = 6,
                            AiCategoryDescription = "A chain is a flexible series of connected metal links forming a continuous strand. Chains are worn as standalone jewelry or used as the foundation for pendants. Common styles include cable chains with round links, curb chains with flat links, rope chains with twisted construction, and box chains with square links.",
                            Code = "chains",
                            Description = "Necklace and bracelet chains",
                            IsActive = true,
                            Name = "Chains"
                        },
                        new
                        {
                            Id = 7,
                            AiCategoryDescription = "A brooch is a decorative pin with a clasp mechanism on the back, designed to attach to clothing or fabric. Brooches can be floral designs, geometric shapes, animal figures, or abstract forms. They sit flat against fabric and serve as visible decorative accents on lapels, collars, or other garment areas.",
                            Code = "brooches",
                            Description = "Decorative brooches and pins",
                            IsActive = true,
                            Name = "Brooches"
                        },
                        new
                        {
                            Id = 8,
                            AiCategoryDescription = "Cufflinks are pairs of decorative fasteners used to secure the cuffs of dress shirts. They consist of a decorative front face connected to a backing mechanism that passes through buttonholes. Cufflinks are typically worn in formal settings and feature geometric, engraved, or stone-set designs.",
                            Code = "cufflinks",
                            Description = "Cufflinks and tie accessories",
                            IsActive = false,
                            Name = "Cufflinks"
                        },
                        new
                        {
                            Id = 9,
                            AiCategoryDescription = "Piercing jewelry is designed for body piercings beyond standard earlobe piercings, including cartilage, nose, lip, eyebrow, navel, and other locations. Common styles include labret studs with flat backs, small hoops, straight and curved barbells. These pieces are typically small, secure, and designed for continuous wear.",
                            Code = "piercing",
                            Description = "Body piercing jewelry",
                            IsActive = true,
                            Name = "Piercing"
                        },
                        new
                        {
                            Id = 10,
                            AiCategoryDescription = "Hair jewelry includes decorative accessories designed to adorn or secure hair. This includes hair pins with decorative tops, ornate hair combs with stones or metalwork, hair clips, and decorative barrettes. These pieces combine functionality with aesthetic appeal and are visible when worn in hairstyles.",
                            Code = "hair_jewelry",
                            Description = "Hair accessories and ornaments",
                            IsActive = true,
                            Name = "Hair jewelry"
                        },
                        new
                        {
                            Id = 11,
                            AiCategoryDescription = "A jewelry set is a coordinated collection of matching pieces designed to be worn together, such as a necklace and earrings, or a ring and bracelet combination. Sets share design elements, materials, and style to create a cohesive look.",
                            Code = "sets",
                            Description = "Matching jewelry sets",
                            IsActive = false,
                            Name = "Sets"
                        },
                        new
                        {
                            Id = 12,
                            AiCategoryDescription = "Men's jewelry includes pieces designed with masculine proportions and aesthetic, such as heavier chain necklaces, substantial link bracelets, bold signet rings, and cufflinks. These pieces typically feature larger dimensions, stronger lines, and more substantial construction compared to traditional jewelry.",
                            Code = "mens_jewelry",
                            Description = "Jewelry designed for men",
                            IsActive = true,
                            Name = "Men's jewelry"
                        },
                        new
                        {
                            Id = 13,
                            AiCategoryDescription = "Custom jewelry encompasses unique, made-to-order pieces designed specifically for an individual customer. These pieces can be any category but are characterized by personalized design elements, custom proportions, unique stone arrangements, or special engravings that make them one-of-a-kind creations.",
                            Code = "custom",
                            Description = "Unique custom-made jewelry",
                            IsActive = false,
                            Name = "Custom Designs"
                        },
                        new
                        {
                            Id = 14,
                            AiCategoryDescription = "Cross pendants are religious or symbolic jewelry pieces in the shape of a cross, designed to hang from a chain. They range from simple Latin crosses with clean lines to elaborate Orthodox crosses with multiple bars, and can be plain metal or embellished with stones. Cross pendants serve both as expressions of faith and as decorative jewelry.",
                            Code = "cross_pendants",
                            Description = "Religious cross pendants and charms",
                            IsActive = true,
                            Name = "Cross pendants"
                        });
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EstimatedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BaseModelId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("UserId");

                    b.ToTable("JewelryConfigurations");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfigurationEngraving", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<string>("FontName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("SizeMm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("JewelryConfigurationEngravings");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfigurationStone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CaratWeight")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("PlacementDataJson")
                        .HasColumnType("text");

                    b.Property<int>("PositionIndex")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SizeMm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("StoneTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId")
                        .HasDatabaseName("IX_ConfigurationStones_ConfigurationId");

                    b.HasIndex("StoneTypeId");

                    b.ToTable("JewelryConfigurationStones");
                });

            modelBuilder.Entity("JewerlyBack.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("Karat")
                        .HasColumnType("integer");

                    b.Property<string>("MetalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PriceFactor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "gold_14k_yellow",
                            ColorHex = "#FFD700",
                            IsActive = true,
                            Karat = 14,
                            MetalType = "gold",
                            Name = "14K Yellow Gold",
                            PriceFactor = 1.0m
                        },
                        new
                        {
                            Id = 2,
                            Code = "gold_18k_yellow",
                            ColorHex = "#FFDF00",
                            IsActive = true,
                            Karat = 18,
                            MetalType = "gold",
                            Name = "18K Yellow Gold",
                            PriceFactor = 1.2m
                        },
                        new
                        {
                            Id = 3,
                            Code = "gold_14k_white",
                            ColorHex = "#E5E4E2",
                            IsActive = true,
                            Karat = 14,
                            MetalType = "gold",
                            Name = "14K White Gold",
                            PriceFactor = 1.05m
                        },
                        new
                        {
                            Id = 4,
                            Code = "gold_18k_white",
                            ColorHex = "#E8E8E8",
                            IsActive = true,
                            Karat = 18,
                            MetalType = "gold",
                            Name = "18K White Gold",
                            PriceFactor = 1.25m
                        },
                        new
                        {
                            Id = 5,
                            Code = "gold_14k_rose",
                            ColorHex = "#B76E79",
                            IsActive = true,
                            Karat = 14,
                            MetalType = "gold",
                            Name = "14K Rose Gold",
                            PriceFactor = 1.05m
                        },
                        new
                        {
                            Id = 6,
                            Code = "gold_18k_rose",
                            ColorHex = "#C9A0A0",
                            IsActive = true,
                            Karat = 18,
                            MetalType = "gold",
                            Name = "18K Rose Gold",
                            PriceFactor = 1.25m
                        },
                        new
                        {
                            Id = 7,
                            Code = "platinum",
                            ColorHex = "#E5E4E2",
                            IsActive = true,
                            MetalType = "platinum",
                            Name = "Platinum",
                            PriceFactor = 1.4m
                        },
                        new
                        {
                            Id = 8,
                            Code = "silver_925",
                            ColorHex = "#C0C0C0",
                            IsActive = true,
                            MetalType = "silver",
                            Name = "Sterling Silver 925",
                            PriceFactor = 0.6m
                        },
                        new
                        {
                            Id = 9,
                            Code = "titanium",
                            ColorHex = "#878681",
                            IsActive = true,
                            MetalType = "titanium",
                            Name = "Titanium",
                            PriceFactor = 0.8m
                        });
                });

            modelBuilder.Entity("JewerlyBack.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("JewerlyBack.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ItemPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("JewerlyBack.Models.StoneType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("DefaultPricePerCarat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("StoneTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "diamond",
                            Color = "Clear",
                            DefaultPricePerCarat = 5000.0m,
                            IsActive = true,
                            Name = "Diamond"
                        },
                        new
                        {
                            Id = 2,
                            Code = "sapphire",
                            Color = "Blue",
                            DefaultPricePerCarat = 1500.0m,
                            IsActive = true,
                            Name = "Sapphire"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ruby",
                            Color = "Red",
                            DefaultPricePerCarat = 1800.0m,
                            IsActive = true,
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = 4,
                            Code = "emerald",
                            Color = "Green",
                            DefaultPricePerCarat = 2000.0m,
                            IsActive = true,
                            Name = "Emerald"
                        },
                        new
                        {
                            Id = 5,
                            Code = "moissanite",
                            Color = "Clear",
                            DefaultPricePerCarat = 400.0m,
                            IsActive = true,
                            Name = "Moissanite"
                        },
                        new
                        {
                            Id = 6,
                            Code = "topaz",
                            Color = "Blue",
                            DefaultPricePerCarat = 250.0m,
                            IsActive = true,
                            Name = "Topaz"
                        },
                        new
                        {
                            Id = 7,
                            Code = "amethyst",
                            Color = "Purple",
                            DefaultPricePerCarat = 150.0m,
                            IsActive = true,
                            Name = "Amethyst"
                        },
                        new
                        {
                            Id = 8,
                            Code = "citrine",
                            Color = "Yellow",
                            DefaultPricePerCarat = 180.0m,
                            IsActive = true,
                            Name = "Citrine"
                        },
                        new
                        {
                            Id = 9,
                            Code = "aquamarine",
                            Color = "Light Blue",
                            DefaultPricePerCarat = 300.0m,
                            IsActive = true,
                            Name = "Aquamarine"
                        },
                        new
                        {
                            Id = 10,
                            Code = "garnet",
                            Color = "Deep Red",
                            DefaultPricePerCarat = 200.0m,
                            IsActive = true,
                            Name = "Garnet"
                        });
                });

            modelBuilder.Entity("JewerlyBack.Models.UploadedAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("UserId");

                    b.ToTable("UploadedAssets");
                });

            modelBuilder.Entity("JewerlyBack.Models.AiPreviewJob", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryConfiguration", "Configuration")
                        .WithMany()
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryBaseModel", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryCategory", "Category")
                        .WithMany("BaseModels")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfiguration", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryBaseModel", "BaseModel")
                        .WithMany("Configurations")
                        .HasForeignKey("BaseModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JewerlyBack.Models.Material", "Material")
                        .WithMany("Configurations")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JewerlyBack.Models.AppUser", "User")
                        .WithMany("Configurations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseModel");

                    b.Navigation("Material");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfigurationEngraving", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryConfiguration", "Configuration")
                        .WithMany("Engravings")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfigurationStone", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryConfiguration", "Configuration")
                        .WithMany("Stones")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewerlyBack.Models.StoneType", "StoneType")
                        .WithMany("ConfigurationStones")
                        .HasForeignKey("StoneTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("StoneType");
                });

            modelBuilder.Entity("JewerlyBack.Models.Order", b =>
                {
                    b.HasOne("JewerlyBack.Models.AppUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JewerlyBack.Models.OrderItem", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryConfiguration", "Configuration")
                        .WithMany("OrderItems")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JewerlyBack.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("JewerlyBack.Models.UploadedAsset", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryConfiguration", "Configuration")
                        .WithMany("Assets")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JewerlyBack.Models.AppUser", "User")
                        .WithMany("Assets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JewerlyBack.Models.AppUser", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Configurations");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryBaseModel", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryCategory", b =>
                {
                    b.Navigation("BaseModels");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfiguration", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Engravings");

                    b.Navigation("OrderItems");

                    b.Navigation("Stones");
                });

            modelBuilder.Entity("JewerlyBack.Models.Material", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("JewerlyBack.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("JewerlyBack.Models.StoneType", b =>
                {
                    b.Navigation("ConfigurationStones");
                });
#pragma warning restore 612, 618
        }
    }
}
