// <auto-generated />
using System;
using JewerlyBack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JewerlyBack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251124175055_UpdateJewelryCategoriesSeed")]
    partial class UpdateJewelryCategoriesSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JewerlyBack.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Provider", "ExternalId")
                        .HasFilter("\"Provider\" IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryBaseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PreviewImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("JewelryBaseModels");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("JewelryCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "rings",
                            Description = "Engagement and decorative rings",
                            IsActive = true,
                            Name = "Rings"
                        },
                        new
                        {
                            Id = 2,
                            Code = "earrings",
                            Description = "Various types of earrings",
                            IsActive = true,
                            Name = "Earrings"
                        },
                        new
                        {
                            Id = 3,
                            Code = "pendants",
                            Description = "Pendants and charms",
                            IsActive = true,
                            Name = "Pendants"
                        },
                        new
                        {
                            Id = 4,
                            Code = "necklaces",
                            Description = "Statement and delicate necklaces",
                            IsActive = true,
                            Name = "Necklaces"
                        },
                        new
                        {
                            Id = 5,
                            Code = "bracelets",
                            Description = "Bangles and chain bracelets",
                            IsActive = true,
                            Name = "Bracelets"
                        },
                        new
                        {
                            Id = 6,
                            Code = "chains",
                            Description = "Necklace and bracelet chains",
                            IsActive = true,
                            Name = "Chains"
                        },
                        new
                        {
                            Id = 7,
                            Code = "brooches",
                            Description = "Decorative brooches and pins",
                            IsActive = true,
                            Name = "Brooches"
                        },
                        new
                        {
                            Id = 8,
                            Code = "cufflinks",
                            Description = "Cufflinks and tie accessories",
                            IsActive = true,
                            Name = "Cufflinks"
                        },
                        new
                        {
                            Id = 9,
                            Code = "piercing",
                            Description = "Body piercing jewelry",
                            IsActive = true,
                            Name = "Piercing"
                        },
                        new
                        {
                            Id = 10,
                            Code = "hair_jewelry",
                            Description = "Hair accessories and ornaments",
                            IsActive = true,
                            Name = "Hair Jewelry"
                        },
                        new
                        {
                            Id = 11,
                            Code = "sets",
                            Description = "Matching jewelry sets",
                            IsActive = true,
                            Name = "Sets"
                        },
                        new
                        {
                            Id = 12,
                            Code = "mens_jewelry",
                            Description = "Jewelry designed for men",
                            IsActive = true,
                            Name = "Men's Jewelry"
                        },
                        new
                        {
                            Id = 13,
                            Code = "custom",
                            Description = "Unique custom-made jewelry",
                            IsActive = true,
                            Name = "Custom Designs"
                        });
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EstimatedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BaseModelId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("UserId");

                    b.ToTable("JewelryConfigurations");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfigurationEngraving", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<string>("FontName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("SizeMm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("JewelryConfigurationEngravings");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfigurationStone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CaratWeight")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("PlacementDataJson")
                        .HasColumnType("text");

                    b.Property<int>("PositionIndex")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SizeMm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("StoneTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("StoneTypeId");

                    b.ToTable("JewelryConfigurationStones");
                });

            modelBuilder.Entity("JewerlyBack.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("Karat")
                        .HasColumnType("integer");

                    b.Property<string>("MetalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PriceFactor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "gold_585_yellow",
                            ColorHex = "#FFD700",
                            IsActive = true,
                            Karat = 14,
                            MetalType = "gold",
                            Name = "Золото 585 жёлтое",
                            PriceFactor = 1.0m
                        },
                        new
                        {
                            Id = 2,
                            Code = "gold_585_white",
                            ColorHex = "#E5E4E2",
                            IsActive = true,
                            Karat = 14,
                            MetalType = "gold",
                            Name = "Золото 585 белое",
                            PriceFactor = 1.1m
                        },
                        new
                        {
                            Id = 3,
                            Code = "silver_925",
                            ColorHex = "#C0C0C0",
                            IsActive = true,
                            MetalType = "silver",
                            Name = "Серебро 925",
                            PriceFactor = 0.3m
                        },
                        new
                        {
                            Id = 4,
                            Code = "platinum",
                            ColorHex = "#E5E4E2",
                            IsActive = true,
                            MetalType = "platinum",
                            Name = "Платина",
                            PriceFactor = 2.5m
                        });
                });

            modelBuilder.Entity("JewerlyBack.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("JewerlyBack.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ItemPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("JewerlyBack.Models.StoneType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("DefaultPricePerCarat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("StoneTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "diamond",
                            Color = "Бесцветный",
                            DefaultPricePerCarat = 50000.0m,
                            IsActive = true,
                            Name = "Бриллиант"
                        },
                        new
                        {
                            Id = 2,
                            Code = "sapphire",
                            Color = "Синий",
                            DefaultPricePerCarat = 15000.0m,
                            IsActive = true,
                            Name = "Сапфир"
                        });
                });

            modelBuilder.Entity("JewerlyBack.Models.UploadedAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("UserId");

                    b.ToTable("UploadedAssets");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryBaseModel", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryCategory", "Category")
                        .WithMany("BaseModels")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfiguration", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryBaseModel", "BaseModel")
                        .WithMany("Configurations")
                        .HasForeignKey("BaseModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JewerlyBack.Models.Material", "Material")
                        .WithMany("Configurations")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JewerlyBack.Models.AppUser", "User")
                        .WithMany("Configurations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseModel");

                    b.Navigation("Material");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfigurationEngraving", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryConfiguration", "Configuration")
                        .WithMany("Engravings")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfigurationStone", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryConfiguration", "Configuration")
                        .WithMany("Stones")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewerlyBack.Models.StoneType", "StoneType")
                        .WithMany("ConfigurationStones")
                        .HasForeignKey("StoneTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("StoneType");
                });

            modelBuilder.Entity("JewerlyBack.Models.Order", b =>
                {
                    b.HasOne("JewerlyBack.Models.AppUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JewerlyBack.Models.OrderItem", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryConfiguration", "Configuration")
                        .WithMany("OrderItems")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JewerlyBack.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("JewerlyBack.Models.UploadedAsset", b =>
                {
                    b.HasOne("JewerlyBack.Models.JewelryConfiguration", "Configuration")
                        .WithMany("Assets")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JewerlyBack.Models.AppUser", "User")
                        .WithMany("Assets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JewerlyBack.Models.AppUser", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Configurations");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryBaseModel", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryCategory", b =>
                {
                    b.Navigation("BaseModels");
                });

            modelBuilder.Entity("JewerlyBack.Models.JewelryConfiguration", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Engravings");

                    b.Navigation("OrderItems");

                    b.Navigation("Stones");
                });

            modelBuilder.Entity("JewerlyBack.Models.Material", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("JewerlyBack.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("JewerlyBack.Models.StoneType", b =>
                {
                    b.Navigation("ConfigurationStones");
                });
#pragma warning restore 612, 618
        }
    }
}
